DROP TABLE IF EXISTS usuario;

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(200) NOT NULL,
    telefone VARCHAR(12) NOT NULL,
    email VARCHAR(200) NOT NULL,
    senha VARCHAR(200) NOT NULL,
    foto_url VARCHAR(500),
    funcao VARCHAR(5),
    criado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY(id);
ALTER TABLE usuario ADD CONSTRAINT ck_usuario_funcao CHECK(funcao IN('ADMIN', 'USER'));


INSERT INTO usuario (nome, telefone, email, senha, foto_url, funcao, criado_em, atualizado_em) VALUES
('Janis', '8197905-9036', 'janis@mail.com', '46f94c8de14fb36680850768ff1b7f2a', '4b0a5bindex.jpg', 'ADMIN', '2021-04-18 14:49:16.698882', '2021-04-26 14:49:26.435425'),
('Jimi', '8198765-3094', 'jimi@mail.com', '061fba5bdfc076bb7362616668de87c8', '4cc947jimiprofile.jpg', 'USER', '2021-04-20 14:29:16.749603', '2021-04-26 14:45:12.258211'),
('Bob', '8197654-3996', 'bob@mail.com', '0acf4539a14b3aa27deeb4cbdf6e989f', '46871abobprofile.jpg', 'USER', '2021-04-21 14:46:00.556941', '2021-04-26 14:11:48.999775'),
('Jim', '8198432-2345', 'jim@mail.com', '5f4dcc3b5aa765d61d8327deb882cf99', '7eh3iufymorrison.jpg', 'USER', '2022-07-13 10:23:00.556941', '2021-04-26 14:11:48.999775'),
('Amy''', '8196543243', 'amy@mail.com', 'd8578edf8458ce06fbc5bb76a58c5ca4', '7fury78chnvamy.jpg', 'USER', '2022-09-08 17:42:00.556941', '2021-04-26 14:11:48.999775');